# 例外処理

- [エラーオブジェクト](#エラーオブジェクト)
- [ReferenceError](#referenceerror)
- [throw](#throw)

オーバーヘッドが高いため重要なところに絞って使用する

## エラーオブジェクト
| -              | -                    |
| -------------- | -------------------- |
| Error          |
| EvalError      | eval                 |
| RangeError     | 範囲外               |
| ReferenceError | 宣言されていない変数 |
| SyntaxError    | 文法エラー           |
| TypeError      | データ型が不正       |
| URIError       | URI                  |
| InternalError  |

その他
arguments

try-catch-finally

## ReferenceError
```js
'  ';
try {
  obj;
} catch(e) {
  console.log(e.message); // obj is not defined
  console.log(e instanceof Error); // true
  console.log(e instanceof ReferenceError); // true
} finally {
  console.log('end'); // end
}
```

## throw
```js
  try {
    throw new Error('エラーが発生しました');
  } catch(e) {
    console.log(e.message); // エラーが発生しました
    console.log(e instanceof Error); // true
    console.log(e instanceof ReferenceError); // true
  }

' Errorオブジェクト以外も投げられる ';
try {
  throw 'throwしました';
} catch(e) {
  console.log(e); // throwしました
  console.log(e.message); // undefined 当然
  console.log(e instanceof Error); // true
}
```